### ISSUE TITLE
Weird interaction with Django test runner, enums failing to serialize

### ISSUE THREAD

**Issue by zartux** [takeflight/django-enumchoicefield#2]
Hi. I didn't know this before, but there's a part of Django's default test runner where Django will run your migrations and then serialize the entire contents of the database to a JSON string. Django does this to support rollbacks on databases that don't have transactions.

I'm working on a new Django 1.10 project with Python 3.5, and one of our migrations creates some records that use enums. Running `./manage.py test` errors out with the attached stack trace.

[stacktrace.txt](https://github.com/takeflight/django-enumchoicefield/files/515101/stacktrace.txt)

I did some debugging in that stack. My current theory is that there's a part of enum records that can't be serialized, perhaps because of some detail about the EnumChoiceField class.

Does that seem plausible and/or familiar? I'll be investigating more, but wanted to ask.

**Comment by timheap** [comment]
Your theory sounds very plausible. Could you add a test to the test suite for this project that replicates the failure you are observing? That way I can also see the failure and help debug it. Either attaching it as a comment to this issue, or making a pull request would help a lot.
